# 改变数据形态
本节内容要囊括的功能：

* 改变形态

    array[np.newaxis, :]；
    array.reshape()；
    array.ravel(), array.flatten()；
    array.transpose()；

* 合并

    np.column_stack()； np.row_stack()；
    np.vstack()； np.hstack()； np.stack()；
    np.concatenate()；

* 拆解

    np.vsplit()； np.hsplit()； np.split()

### 1 改变形态

In [2]:
# 变维度
import numpy as np

a = np.array([1,2,3,4,5,6])
a_2d = a[np.newaxis, :] 
"""
np.newaxis放在第一个位置，表示在0维（行维度）前面插入一个新维度，
：表示保留原数组所有元素。
"""
print(a.shape, a_2d.shape)
print(a)
print(a_2d)


(6,) (1, 6)
[1 2 3 4 5 6]
[[1 2 3 4 5 6]]


In [ ]:
a = np.array([1,2,3,4,5,6])
a_none = a[:, None] # None在后面表示在列维度插入新维度。
a_expand = np.expand_dims(a, axis=1) # axis=1表示增加列
print(a_none.shape, a_expand.shape)
print(a_none)
print(a_expand)

"""axis=1 参数指定在第2个维度（索引从0开始）的位置增加一个维度
对于一维数组，axis=0会在前面增加维度（形状变为(1,6)），
而axis=1会在后面增加维度（形状变为(6,1)）
"""

(6, 1) (6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


'axis=1 参数指定在第2个维度（索引从0开始）的位置增加一个维度\n对于一维数组，axis=0会在前面增加维度（形状变为(1,6)），\n而axis=1会在后面增加维度（形状变为(6,1)）\n'

In [5]:
a = np.array([1,2,3,4,5,6])
a1 = a.reshape([2, 3])
a2 = a.reshape([3,1,2]) # 表示将数组重塑为三维
a3 = a.reshape([3,2,1]) # 表示将数组重塑为三维
"""我理解了，[3，2，1]中，3相当于是测试测了几次，2是测了几个参数，1是测试几个对象，这个数据的形态需要在脑海里想一想。
"""

print("a1 shape:", a1.shape)
print(a1)
print("a2 shape:", a2.shape)
print(a2)
print("a3 shape:", a3.shape)
print(a3)

# 三维的解释 https://zhuanlan.zhihu.com/p/670002054
# 更精细的解释 https://zhuanlan.zhihu.com/p/31275071

a1 shape: (2, 3)
[[1 2 3]
 [4 5 6]]
a2 shape: (3, 1, 2)
[[[1 2]]

 [[3 4]]

 [[5 6]]]
a3 shape: (3, 2, 1)
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [13]:
# 矩阵转置
a = np.array([1,2,3,4,5,6]).reshape([2, 3])
aT1 = a.T
aT2 = np.transpose(a)

print(aT1)
print(aT2)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


### 2 合并

In [14]:
feature_a = np.array([1,2,3,4,5,6])
feature_b = np.array([11,22,33,44,55,66])
c_stack = np.column_stack([feature_a, feature_b])
print(c_stack)


[[ 1 11]
 [ 2 22]
 [ 3 33]
 [ 4 44]
 [ 5 55]
 [ 6 66]]


In [17]:
sample_a = np.array([0, 1.1])
sample_b = np.array([1, 2.2])
c_stack = np.row_stack([sample_a, sample_b])
print(c_stack)

[[0.  1.1]
 [1.  2.2]]


C:\Users\shiyan\AppData\Local\Temp\ipykernel_28288\248112683.py:3: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  c_stack = np.row_stack([sample_a, sample_b])


In [18]:
feature_a = np.array([1,2,3,4,5,6])[:, None]
feature_b = np.array([11,22,33,44,55,66])[:, None]
c_stack = np.hstack([feature_a, feature_b])
print(c_stack)

sample_a = np.array([0, 1.1])[None, :]
sample_b = np.array([1, 2.2])[None, :]
c_stack = np.vstack([sample_a, sample_b])
print(c_stack)

[[ 1 11]
 [ 2 22]
 [ 3 33]
 [ 4 44]
 [ 5 55]
 [ 6 66]]
[[0.  1.1]
 [1.  2.2]]


### np.concatenate()
np.concatenate() 是我最喜欢的方法，管它什么 vstack hstack 甚至是在更高维度上要合并， 我们都可以用 concatenate() 一个功能实现。

In [19]:
a = np.array([
[1,2],
[3,4]
])
b = np.array([
[5,6],
[7,8]
])

print(np.concatenate([a, b], axis=0))
print(np.concatenate([a, b], axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


### 3 拆解
能横着，竖着合并，那也能横着竖着拆解。np.vsplit() 和 np.hsplit() 就是干这事的。 如果直接在 indices_or_sections 后填入数字，就是要整分的段数， 而如果接着的是一个列表，那就按照列表中的 index 来取区间。

In [20]:
a = np.array(
[[ 1, 11, 2, 22],
 [ 3, 33, 4, 44],
 [ 5, 55, 6, 66],
 [ 7, 77, 8, 88]]
)
print(np.vsplit(a, indices_or_sections=2))  # 分成两段
print(np.vsplit(a, indices_or_sections=[2,3]))  # 分片成 [:2]，[2:3], [3:]


[array([[ 1, 11,  2, 22],
       [ 3, 33,  4, 44]]), array([[ 5, 55,  6, 66],
       [ 7, 77,  8, 88]])]
[array([[ 1, 11,  2, 22],
       [ 3, 33,  4, 44]]), array([[ 5, 55,  6, 66]]), array([[ 7, 77,  8, 88]])]
