# 疫情数据分析

In [2]:
with open('archive/day_wise.csv', 'r', encoding='utf-8') as f:
    data = f.readlines() # 读取所有行

covid = { # 定义一个字典，用于存储数据
    "date": [], # 日期
    "data": [], # 数据
    "header": [h for h in data[0].split(",") [1:]], # 头部
}

for row in data[1:]: # 遍历每一行数据
    split_row = row.strip().split(",") # 按逗号分隔,strip()去除换行符
    covid["date"].append(split_row[0]) # 日期在第一列
    covid["data"].append([float(n) for n in split_row[1:]]) # 数据在第二列开始


In [3]:
covid['header']

['Confirmed',
 'Deaths',
 'Recovered',
 'Active',
 'New cases',
 'New deaths',
 'New recovered',
 'Deaths / 100 Cases',
 'Recovered / 100 Cases',
 'Deaths / 100 Recovered',
 'No. of countries\n']

In [4]:
covid['date']

['2020-01-22',
 '2020-01-23',
 '2020-01-24',
 '2020-01-25',
 '2020-01-26',
 '2020-01-27',
 '2020-01-28',
 '2020-01-29',
 '2020-01-30',
 '2020-01-31',
 '2020-02-01',
 '2020-02-02',
 '2020-02-03',
 '2020-02-04',
 '2020-02-05',
 '2020-02-06',
 '2020-02-07',
 '2020-02-08',
 '2020-02-09',
 '2020-02-10',
 '2020-02-11',
 '2020-02-12',
 '2020-02-13',
 '2020-02-14',
 '2020-02-15',
 '2020-02-16',
 '2020-02-17',
 '2020-02-18',
 '2020-02-19',
 '2020-02-20',
 '2020-02-21',
 '2020-02-22',
 '2020-02-23',
 '2020-02-24',
 '2020-02-25',
 '2020-02-26',
 '2020-02-27',
 '2020-02-28',
 '2020-02-29',
 '2020-03-01',
 '2020-03-02',
 '2020-03-03',
 '2020-03-04',
 '2020-03-05',
 '2020-03-06',
 '2020-03-07',
 '2020-03-08',
 '2020-03-09',
 '2020-03-10',
 '2020-03-11',
 '2020-03-12',
 '2020-03-13',
 '2020-03-14',
 '2020-03-15',
 '2020-03-16',
 '2020-03-17',
 '2020-03-18',
 '2020-03-19',
 '2020-03-20',
 '2020-03-21',
 '2020-03-22',
 '2020-03-23',
 '2020-03-24',
 '2020-03-25',
 '2020-03-26',
 '2020-03-27',
 '2020-03-

In [5]:
covid['data'][:5] # 获取前5行数据

[[555.0, 17.0, 28.0, 510.0, 0.0, 0.0, 0.0, 3.06, 5.05, 60.71, 6.0],
 [654.0, 18.0, 30.0, 606.0, 99.0, 1.0, 2.0, 2.75, 4.59, 60.0, 8.0],
 [941.0, 26.0, 36.0, 879.0, 287.0, 8.0, 6.0, 2.76, 3.83, 72.22, 9.0],
 [1434.0, 42.0, 39.0, 1353.0, 493.0, 16.0, 3.0, 2.93, 2.72, 107.69, 11.0],
 [2118.0, 56.0, 52.0, 2010.0, 684.0, 14.0, 13.0, 2.64, 2.46, 107.69, 13.0]]

In [6]:
print(covid['data'][:5])

[[555.0, 17.0, 28.0, 510.0, 0.0, 0.0, 0.0, 3.06, 5.05, 60.71, 6.0], [654.0, 18.0, 30.0, 606.0, 99.0, 1.0, 2.0, 2.75, 4.59, 60.0, 8.0], [941.0, 26.0, 36.0, 879.0, 287.0, 8.0, 6.0, 2.76, 3.83, 72.22, 9.0], [1434.0, 42.0, 39.0, 1353.0, 493.0, 16.0, 3.0, 2.93, 2.72, 107.69, 11.0], [2118.0, 56.0, 52.0, 2010.0, 684.0, 14.0, 13.0, 2.64, 2.46, 107.69, 13.0]]


In [ ]:
# 获取2020-2-3的所有数据
print("日期列表摘录：", covid['date'][:4])
row_idx = covid['date'].index('2020-02-03') # 获取2020-02-03的索引
print("日期->索引转换：", row_idx) # 打印2020-02-03的索引
print("索引->日期转换：", covid['date'][row_idx]) # 打印2020-02-03的日期

import numpy as np
data = np.array(covid['data'])

for header, number in zip(covid['header'], data[date_idx]): # 遍历日期对应的数据
    print(f'{header}: {number}')

日期列表摘录： ['2020-01-22', '2020-01-23', '2020-01-24', '2020-01-25']
日期->索引转换： 12
索引->日期转换： 2020-02-03
Confirmed: 19887.0
Deaths: 426.0
Recovered: 604.0
Active: 18857.0
New cases: 3100.0
New deaths: 64.0
New recovered: 145.0
Deaths / 100 Cases: 2.14
Recovered / 100 Cases: 3.04
Deaths / 100 Recovered: 70.53
No. of countries
: 25.0


In [14]:
# 累计确诊
row_idx = covid['date'].index('2020-01-24') # 获取日期索引
column_idx = covid['header'].index('Confirmed')
confirmed0124 = data[row_idx, column_idx] # 获取2020-01-24的累计确诊人数
print("2020-01-24的累计确诊人数：", confirmed0124)

2020-01-24的累计确诊人数： 941.0


In [15]:
# 新增死亡 “New deaths”
row_idx = covid['date'].index('2020-07-23')
column_idx = covid['header'].index('New deaths')
new_deaths_0723 = data[row_idx, column_idx]
print("2020-07-23的新增死亡人数：", new_deaths_0723)


2020-07-23的新增死亡人数： 9966.0


In [18]:
# 从 1 月 25 日到 7 月 22 日，一共增长了多少确诊病例？
row_idx_start = covid['date'].index('2020-01-25')
row_idx_end = covid['date'].index('2020-07-22')
new_cases_idx = covid['header'].index('New cases')

new_cases = data[row_idx_start+1:row_idx_end+1, new_cases_idx]
overall = new_cases.sum()
print(f'2020年1月25日至2020年7月22日之间，累计新增确诊为{overall}例。')

2020年1月25日至2020年7月22日之间，累计新增确诊为15247309.0例。


# 数据清洗

In [21]:
# 原始数据
raw_data = [
["Name", "StudentID", "Age", "AttendClass", "Score"],
["小明", 20131, 10, 1, 67],
["小花", 20132, 11, 1, 88],
["小菜", 20133, None, 1, "98"],
["小七", 20134, 8, 1, 110],
["花菜", 20134, 98, 0, None],
["刘欣", 20136, 12, 0, 12]
]

raw_data

[['Name', 'StudentID', 'Age', 'AttendClass', 'Score'],
 ['小明', 20131, 10, 1, 67],
 ['小花', 20132, 11, 1, 88],
 ['小菜', 20133, None, 1, '98'],
 ['小七', 20134, 8, 1, 110],
 ['花菜', 20134, 98, 0, None],
 ['刘欣', 20136, 12, 0, 12]]

 Numpy 面对大数据时，它得天独厚的计算速度优势了。同样一份 1GB 的数据，Python List 处理起来可能要 1 小时， Numpy 优化后，速度可以成倍增长。

In [ ]:
import numpy as np
data = np.array(raw_data)
data # 结果里有 dtype=object ，说明数据类型是object，即对象，无法参与Numpy的运算，只有dtype是int，float这种才行。

array([['Name', 'StudentID', 'Age', 'AttendClass', 'Score'],
       ['小明', 20131, 10, 1, 67],
       ['小花', 20132, 11, 1, 88],
       ['小菜', 20133, None, 1, '98'],
       ['小七', 20134, 8, 1, 110],
       ['花菜', 20134, 98, 0, None],
       ['刘欣', 20136, 12, 0, 12]], dtype=object)

In [ ]:
# 数据预处理
data_process = []
for i in range(len(raw_data)):
    if i == 0:
        continue    # 不要首行字符串
    # 去掉首列名字
    data_process.append(raw_data[i][1:])
data = np.array(data_process, dtype=np.float64) # 这里只有float能转换None，int不能。
print("data.dtype", data.dtype)
print(data) 

data.dtype float64
[[2.0131e+04 1.0000e+01 1.0000e+00 6.7000e+01]
 [2.0132e+04 1.1000e+01 1.0000e+00 8.8000e+01]
 [2.0133e+04        nan 1.0000e+00 9.8000e+01]
 [2.0134e+04 8.0000e+00 1.0000e+00 1.1000e+02]
 [2.0134e+04 9.8000e+01 0.0000e+00        nan]
 [2.0136e+04 1.2000e+01 0.0000e+00 1.2000e+01]]


In [25]:
# 数据清洗
sid = data[:,0]# 括号里意思是 获取data的0列，即所有行的第0列，即所有学生的学号。
unique,counts = np.unique(sid,return_counts=True)
print(counts)
print(unique[counts>1]) # 打印出重复的学号


[1 1 1 2 1]
[20134.]


In [26]:
# 根据清洗结果修改数值
data[4, 0] = 20135 
print(data)

[[2.0131e+04 1.0000e+01 1.0000e+00 6.7000e+01]
 [2.0132e+04 1.1000e+01 1.0000e+00 8.8000e+01]
 [2.0133e+04        nan 1.0000e+00 9.8000e+01]
 [2.0134e+04 8.0000e+00 1.0000e+00 1.1000e+02]
 [2.0135e+04 9.8000e+01 0.0000e+00        nan]
 [2.0136e+04 1.2000e+01 0.0000e+00 1.2000e+01]]


In [ ]:
# 清洗年龄
is_nan = np.isnan(data[:,1])
print("is_nan:", is_nan)
nan_idx = np.argwhere(is_nan)

# 计算有数据的平均年龄，用 ~ 符号可以 True/False 对调
mean_age = data[~np.isnan(data[:,1]), 1].mean() # ~ 符号可以 True/False 对调，这里用于筛选数据。
print("有数据的平均年龄：", mean_age)

is_nan: [False False  True False False False]
有数据的平均年龄： 27.8
